In [13]:
\
!pip install numpy



In [27]:
import numpy as np

Ty=list(np.arange(10))
print(Ty)

[np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9)]


In [33]:
#1
#a
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
#1
#b
np.arange(0.5,5,0.25)

array([0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ,
       3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75])

In [39]:
# 2
#a
print(np.zeros(10))

# b
ar= np.zeros(12)
np.reshape(ar, (3, 4))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
# 3
#a
print(np.linspace(2, 12, 5, dtype=int)) 

# b
print(np.linspace(3, 9, 4, dtype=int)) 

[ 2  4  7  9 12]
[3 5 7 9]


In [13]:
# 4
#a
ae=np.random.rand(4, 2)

#b
import numpy as np

(np.random.rand(3, 3) * 10).astype(int)




array([[4, 5, 8],
       [5, 7, 7],
       [6, 3, 7]])

In [15]:
aq=np.reshape(ae, (1, 8))
print(aq)
# חשוב להשים לב שבפעולת  reshape ! המספר הכולל של האיברים לפני ואחרי ה־reshape  חייב להיות זהה.
#אם לא היו מספרים תואמים נקבל שגיאה.


[[0.66557765 0.80652825 0.73193037 0.50187579 0.87940397 0.33898041
  0.11541868 0.71747082]]


In [ ]:
# 5
# אם נגריל  מספריים אקראים על מספר אחד נתון כל מי שיעשה את אותה פעולה יקבל את אותה  תשובה בגלל שפעולה הזו עובדת על אלגוריתם מטמטי
# היתרון שכל אחד יעשה את הפעולה הזו יקבל את אותה הרצה אם רוצים לעבוד יחד על אותו נתון לדוגמא.